fixing bad directory listing, setting for negative test

diff --git a/Jenkinsfile5h b/Jenkinsfile5h
--- a/Jenkinsfile5h
+++ b/Jenkinsfile5h
@@ -946,6 +946,7 @@ node('master') {
 
                     def fragid = ''
                     msg = ''
+                    trip = false
 
                     if (FRAGMENT_ID.length() > 0) {
                         fragid = FRAGMENT_ID
@@ -962,13 +963,16 @@ node('master') {
                             msg += "\nMatching Fragment ${fragid} found."
                         } else {
                             msg += "\nNO fragment ${fragid} found."
-                            error("Changelog fragment error: fragment not added")
+                            trip = true
                         }
                     }else {
                         msg += "\nNO fragment id found.. skipping test"
                     }
-                    echo "${msg}"
+                    echo "Result: " + msg
                     echo '--------------------------------------------------------------------------'
+                    if (trip ) {
+                        error("Changelog fragment error: fragment not added")
+                    }
                 }
             }
         }
@@ -1141,20 +1145,19 @@ node('master') {
                                 if (VERBOSITY.toBoolean()){
                                     echo '\r\n Pre-test configuration data---------------------vvv'
                                     out = sh (script: "set | grep -i ansib || true", returnStdout: true)
-                                    echo out
+                                    echo 'environment: ' + out
                                     out = sh (script: "ansible-config dump 2>&1 || true", returnStdout: true)
                                     echo out
                                     out = sh (script: "ansible-galaxy --version 2>&1 || true", returnStdout: true)
                                     echo out
                                     out = sh (script: "ansible-galaxy collection list -v 2>&1 || true", returnStdout: true)
                                     echo out
-                                    out = sh (script: "ls -l /home/jenkins/.ansible/collections/ansible_collections/ || true", returnStdout: true)
-                                    echo out
+                                    // out = sh (script: "ls -l ${env.WORKSPACE}/${REPO}/collections/ansible_collections/ || true", returnStdout: true)
+                                    // echo out
                                     out = sh (script: "cat ${env.WORKSPACE}/${REPO}/configuration.yml || true", returnStdout: true)
-                                    echo "on build box: "
-                                    echo out
+                                    echo "config on build box: " + out
                                     out = "${env.WORKSPACE}/${REPO}"
-                                    echo out
+                                    echo "test zone: " + out
                                     out = sh (script: "python3 -m pytest --version 2>&1 || true", returnStdout: true)
                                     echo out
                                     echo '\r\n Pre-test configuration data---------------------^^^'
